config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth/callbacks' }

  devise_scope :user do
    match 'create_user' => 'omniauth/callbacks#create_user', as: :create_user, via: :post
    match 'user_prompt' => 'omniauth/callbacks#user_prompt', as: :user_prompt, via: :get
  end

  devise_scope :user do
    mount Shoppe::Engine => "/shoppe"
  end

  get 'welcome/index'
  get 'about_us', to: 'welcome#about_us', as: 'about_us'
  get 'blog' => redirect("http://blog.gofourwalls.com"), as: 'blog'
  get 'account', to: 'welcome#account', as: 'account'

  resources :charges

  resources :products, only: [:index, :show] do
    member do
      post 'buy'
    end
    collection do
      get 'get_product'
    end
  end
  post 'products/destroy_img' => 'products#destroy_img'

  get "room_type", to: "product_categories#index_type"
  get "room_size", to: "product_categories#index_size"
  get "category_tree", to: "product_categories#category_tree"
  resources :product_categories, only: [:show]
  get "cart", to: "orders#show"
  delete "cart", to: "orders#destroy"
  post 'cart/:order_item_id', to: 'orders#remove', as: :remove_from_order

  match "checkout", to: "orders#checkout", as: "checkout", via: [:get, :patch]
  match "checkout/pay", to: "orders#payment", as: "checkout_payment", via: [:get, :post]
  match "checkout/confirm", to: "orders#confirmation", as: "checkout_confirmation", via: [:get, :post]
  match "order/:id/refresh_items", to: "orders#refresh_items", as: "refresh_order_items", via: [:get, :post]
  post "check_country", to: "orders#check_country", as: "check_country"
  post 'country_changing', to: 'orders#country_changing'
  post 'change_currency_checkout', to: 'orders#change_currency_checkout'
  post 'change_user_country', to: 'welcome#change_user_country'

  get 'room_editor', to: 'room#index'
  get 'room_editor/edit', to: 'room#edit'
  post 'room_editor/save', to: 'room#save'

  get 'designer-portal', to: 'design_projects#project_info'
  get 'designer-portal/select_items', to: 'design_projects#select_items'
  get 'designer-portal/room_builder', to: 'design_projects#room_builder'
  get 'designer-portal/instructions', to: 'design_projects#instructions'
  post 'designer-portal/create', to: 'design_projects#create'
  patch 'designer-portal/create', to: 'design_projects#create'
  patch 'designer-portal/add_to_room_builder', to: 'design_projects#add_to_room_builder'
  post 'designer-portal/items_filtering', to: 'design_projects#items_filtering'
  delete 'designer-portal/remove_product', to: 'design_projects#remove_product'

  get 'designer-portal/create_new', to: 'design_projects#create_new'

  patch 'designer-portal/save_room_layout', to: 'design_projects#save_room_layout'
  patch 'designer-portal/save_furniture_board', to: 'design_projects#save_furniture_board'
  patch 'designer-portal/layout_submit_room', to: 'design_projects#layout_submit_room'
  patch 'designer-portal/board_submit_room', to: 'design_projects#board_submit_room'

  get 'design_portals/:id', to: 'design_projects#edit'
  
  root 'welcome#index'

  get 'search', to: 'search#index'
  post 'change_user_country', to: 'welcome#change_user_country'

end

app/models/design_project.rb
class DesignProject < Shoppe::DesignProject
    
 
end

app/models/user.rb
class User < Shoppe::User

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable,
         :omniauthable, :validatable
  
  has_many :reviews, dependent: :destroy
  has_many :products, through: :reviews
  validates_uniqueness_of :email_address

  def self.build_with_auth_data(auth_data, params)
    password = Devise.friendly_token.first(8)
    first_name = auth_data['info']['name'].split[0]
    last_name = auth_data['info']['name'].split[1]


    user = self.new(email: params.try(:[], "user").try(:[], "email") || auth_data['info']['email'],
             :first_name => first_name, :last_name => last_name,
             :password => password ,
             :password_confirmation => password,
             auth_data['provider'] => auth_data['uid']
            )
  end

  def fullname
   first_name + ' ' + last_name
  end

  alias_attribute :email, :email_address
  alias_attribute :email=, :email_address=
  alias_attribute :email_changed?, :email_address_changed?

end

app/controllers/design_projects_controller.rb
class DesignProjectsController < ApplicationController
 load_and_authorize_resource
    before_filter { (params[:id] && @design_project = DesignProject.find(params[:id])) ||
                    (session[:design_project_id] && @design_project = DesignProject.find(session[:design_project_id]) )
                  }
    before_filter :check_session_contain_project, only: [:create]
    before_filter :check_user_access, if: :design_project_present

  def create
    @design_project = DesignProject.new(design_project_params)
    @design_project.user = current_user
    @design_project.status = :draft
    if @result = @design_project.save
      session[:design_project_id] = @design_project.id
      @redirect_url = params[:redirect_to_link]
      respond_to do |format|
        format.html { redirect_to designer_portal_path }
        format.js
      end
    else
      respond_to do |format|
        format.html { render action: :project_info }
        format.js { render status: 422 }
      end
    end
  end

  def check_user_access
    unless current_user.admin? || (@design_project.user && @design_project.user.id == current_user.id)
      flash[:alert] = "Access denied. You are not authorized to access this design project. "
      redirect_to root_path
    end
  end

  def design_project_present
    @design_project.present?
  end

  def update
    @design_project.assign_attributes(design_project_params)
    @result = @design_project.changed? ? @design_project.save : @design_project.valid?
    if @result
      @redirect_url = params[:redirect_to_link]
      respond_to do |format|
        format.html { redirect_to designer_portal_path }
        format.js
      end
    else
      respond_to do |format|
        format.html { render action: :project_info }
        format.js { render status: 422 }
      end
    end
  end

  def save_room_layout
    @design_project = DesignProject.find(session[:design_project_id])
    @design_project.width =  params[:room_dimensions][:width] if params[:room_dimensions][:width]
    @design_project.depth =  params[:room_dimensions][:depth] if params[:room_dimensions][:depth]
    @design_project.save
    @design_project.design_projects_products.each do |design_projects_product|
      design_projects_product.layout_posX = nil
      design_projects_product.layout_posY = nil
      design_projects_product.layout_rotation = nil
      design_projects_product.save
    end
    params[:products].each do |product_id, product_params|
      design_projects_product = DesignProjectsProduct.find_or_create_by(product_id: product_id, design_project_id: @design_project.id)
      design_projects_product.layout_posX = product_params['layout_posX'].to_f
      design_projects_product.layout_posY = product_params['layout_posY'].to_f
      design_projects_product.layout_rotation = product_params['layout_rotation'].to_f
      design_projects_product.save
    end
    render json: true
  end

  def save_furniture_board
    @design_project = DesignProject.find(session[:design_project_id])
    @design_project.design_projects_products.each do |design_projects_product|
      design_projects_product.board_width = nil
      design_projects_product.board_depth = nil
      design_projects_product.board_posX = nil
      design_projects_product.board_posY = nil
      design_projects_product.board_rotation = nil
      design_projects_product.save
      puts design_projects_product.board_posY
    end
    params[:products].each do |product_id, product_params|
      design_projects_product = DesignProjectsProduct.find_or_create_by(product_id: product_id, design_project_id: @design_project.id)
      design_projects_product.board_width = product_params['board_width'].to_f
      design_projects_product.board_depth = product_params['board_depth'].to_f
      design_projects_product.board_posX = product_params['board_posX'].to_f
      design_projects_product.board_posY = product_params['board_posY'].to_f
      design_projects_product.board_rotation = product_params['board_rotation'].to_f
      design_projects_product.save
    end
    render json: true
  end

  def board_submit_room
    @design_project = DesignProject.find(session[:design_project_id])
    @design_projects_products_to_remove = DesignProjectsProduct.where(product_id: params[:ids], design_project_id: @design_project.id).destroy_all
    @ids_to_remove = params[:ids]
    @design_project.status = :draft
    @design_project.save
    render json: true
  end

  def layout_submit_room
    @design_project = DesignProject.find(session[:design_project_id])
    @design_projects_products_to_remove = DesignProjectsProduct.where(product_id: params[:ids], design_project_id: @design_project.id).destroy_all
    @ids_to_remove = params[:ids]
    @design_project.status = :revision_requested
    @design_project.save
    render json: true
  end

  def check_session_contain_project
    session[:design_project_id] ? update : create
  end

  def project_info
    session[:design_project_id] = params[:id] if params[:id].present?
    @design_project = session[:design_project_id] ? DesignProject.find(session[:design_project_id]) : DesignProject.new
  end

  def select_items
    # @products_categories = Product.items_filtering(params[:categories], params[:colors], params[:materials])
    @parent_categories = ProductCategory.where(parent_id: nil).order("name")
    @categories = ProductCategory.order("name")
    @colors = Color.order("name")
    @materials = Material.order("name")
    @products_categories = @design_project.product_list_by_filters
  end

  def room_builder
    @design_project = DesignProject.find(session[:design_project_id])
    @products_categories = @design_project.products.includes(:product_category).order('shoppe_product_categories.name').group_by { |t| t.product_category }
  end

  def add_to_room_builder
    @design_project.update(product_ids: params[:product_ids])
    render nothing: true
  end

  def remove_product
    @design_projects_product = DesignProjectsProduct.where( product_id: params[:product_id], design_project_id: params[:design_project_id] ).first
    @design_projects_product.destroy if @design_projects_product
    @product = @design_projects_product.product if @design_projects_product
    respond_to do |format|
      format.js
    end
  end

  def items_filtering
    params[:show_all] ||= false
    @products_categories = Product.items_filtering(params[:categories], params[:colors], params[:materials])
    @design_project.create_filters_by(params[:categories], params[:colors], params[:materials], params[:show_all])
    respond_to do |format|
      format.js
    end
  end

  def instructions
  end

  def create_new
    @design_project = DesignProject.new
    session[:design_project_id] = nil
    redirect_to designer_portal_path
  end

  private

  def design_project_params
    width = ( params[:design_project][:width_ft].to_i * 12 ) + params[:design_project][:width_in].to_i
    depth = ( params[:design_project][:depth_ft].to_i * 12 ) + params[:design_project][:depth_in].to_i
    if params[:save_image] == '0'
      params.require(:design_project).permit(:name, :inspiration, :product_category_id, :url_inspiration_image1, :url_inspiration_image2, :url_inspiration_image3).merge(width: width, depth: depth)
    else
      params.require(:design_project).permit(:name, :inspiration, :inspiration_image1, :inspiration_image2, :inspiration_image3, :product_category_id, :url_inspiration_image1, :url_inspiration_image2, :url_inspiration_image3, :inspiration_image1, :inspiration_image2, :inspiration_image3).merge(width: width, depth: depth)
    end
  end


end

app/helpers/design_projects_helper.rb
module DesignProjectsHelper
end

app/views/design_projects/_product_list.html.erb
<div id='productList'>
  <%= form_for @design_project, :url => designer_portal_add_to_room_builder_path, remote: true do |f| %>
    <%= f.error_messages %>
    <article class="products-grid">
      <div class="products-grid__btn-cont">
        <a class="products-grid__left-btn" >show all</a>
        <!-- <button class="" type="button"></button> -->
        <%= f.submit "Add Selections to Room Builder", :class => 'products-grid__right-btn' %>
      </div>
      <div class="one-products-category l-cont">
        <% @products_categories.each do |category, product_list| %>
          <div class="one-products-category__title l-el"><%= category %></div>
          <% product_list.each do |product| %>
            <div class="one-products-category__product l-el">
              <div class="one-products-category__anch l-cont" href="#">
               <%= image_tag image_link(product, 'default_image'), class: "one-products-category__img l-el", alt: "#{product.full_name}" %>
              </div>
              <label class="one-products-category__label">
                <%= check_box_tag "product_ids[]", product.id, @design_project.products.include?(product) %>
              </label>
            </div>
          <% end %>
        <!--  -->
        <% end %>
      </div>
    </article>
  <% end %>
</div>
<script>
$(document).ready(function(){
 $(".one-products-category__anch").on('click', function () {
    var checkbox = $(this).parent().find('.one-products-category__label > input');
    if (checkbox[0].checked) {
      checkbox.prop('checked', false);
      checkbox[0].parentElement.previousElementSibling.classList.toggle("chosen");
    } else {
      checkbox.prop('checked', true);
      checkbox[0].parentElement.previousElementSibling.classList.add("chosen");
    }
  });
 var checkboxes = document.querySelectorAll(".one-products-category__label > input"),
      filterCategories = document.querySelectorAll(".one-filter-category"),
      categoryNames = document.querySelectorAll(".one-filter-category__name");
  if (checkboxes.length) {
      for (var i = 0, lim = checkboxes.length; i < lim; i += 1) {
          if (checkboxes[i].checked) {
              checkboxes[i].parentElement.previousElementSibling.classList.add("chosen");
          };
          checkboxes[i].addEventListener("change", function() {
              this.parentElement.previousElementSibling.classList.toggle("chosen");
          });
      };
  };
})
</script>

app/views/design_projects/instructions.html.erb
<main>
    <div class="main-tabs">
        <div class="l-wrapper">
            <%= link_to 'project info', designer_portal_path, class: "main-tabs__one-tab", id: 'project-info-tab' %>
            <%= link_to 'select items', designer_portal_select_items_path, class: "main-tabs__one-tab" %>
            <%= link_to 'room builder', designer_portal_room_builder_path, class: "main-tabs__one-tab", id: 'room-builder-tab' %>
            <%= link_to 'instructions', designer_portal_instructions_path, class: "main-tabs__one-tab main-tabs__one-tab--active", id: 'instructions-tab' %>
        </div>
    </div>
    <div class="l-wrapper">
    </div>
</main>

app/views/design_projects/project_info.html.erb
<% content_for :custom_scripts do %>
  <%= javascript_include_tag "specific/designer-portal-ajax.js" %>
<% end %>
<main>
    <section class="main-tabs">
        <div class="l-wrapper">
            <%= link_to 'project info', designer_portal_path, class: "main-tabs__one-tab main-tabs__one-tab--active", id: 'project-info-tab' %>
            <%= link_to 'select items', designer_portal_select_items_path, class: "main-tabs__one-tab save-project-info-tab", id: 'select-items-tab' %>
            <%= link_to 'room builder', designer_portal_room_builder_path, class: "main-tabs__one-tab save-project-info-tab", id: 'room-builder-tab' %>
            <%= link_to 'instructions', designer_portal_instructions_path, class: "main-tabs__one-tab save-project-info-tab", id: 'instructions-tab' %>
        </div>
    </section>
    <div class="l-wrapper">
        <div class="l-tabs-alignment">
            <div class="info-table">
                <div class="info-table__row">
                    <div class="info-table__cell">Project Status:</div>
                    <div class="info-table__cell" id='project-status'><%= @design_project.status.try(:humanize).try(:titleize) %></div>
                </div>
                <div class="info-table__row">
                    <div class="info-table__cell">Creation Date:</div>
                    <div class="info-table__cell"><%= (@design_project.try(:created_at) || Date.today).strftime('%b %d, %Y') %></div>
                </div>
                <div class="info-table__row">
                    <div class="info-table__cell">Last Modefied Date:</div>
                    <div class="info-table__cell"><%= (@design_project.try(:updated_at) || Date.today).strftime('%b %d, %Y') %></div>
                </div>
                <div class="info-table__row">
                    <div class="info-table__cell">Designed By:</div>
                    <div class="info-table__cell"><%= (@design_project.user || current_user).try(:full_name) %></div>
                </div>
                <div class="info-table__row">
                    <div class="info-table__cell">Designer Email:</div>
                    <div class="info-table__cell" id='designer-email'><%= (@design_project.user || current_user).try(:email_address) %></div>
                </div>
            </div>
            <%= form_for @design_project, url: designer_portal_create_path, html: { class: "project-init-info", id: 'project-form', multipart: true }, remote: true do |f| %>
                <div class="project-init-info__row">
                    <div class="project-init-info__cell">Project Name</div>
                    <div class="project-init-info__cell">
                        <label class="project-init-info__label">
                            <%= f.text_field :name, class: "project-init-info__input", id: 'project-name' %>
                        </label>
                    </div>
                    <div class="project-init-info__cell"></div>
                </div>
                <div class="project-init-info__row">
                    <div class="project-init-info__cell">Inspiration</div>
                    <div class="project-init-info__cell">
                        <label class="project-init-info__label">
                            <%= f.text_area :inspiration, class: "project-init-info__textarea", id: 'project-inspiration' %>
                        </label>
                    </div>
                    <div class="project-init-info__cell"></div>
                </div>


                <div class="project-init-info__row">
                    <div class="project-init-info__cell">Inspiration Images</div>
                    <div class="project-init-info__cell">
                        <label class="project-init-info__label">
                            <%= f.text_field "url_inspiration_image1", id: "project-url-inspiration-image1", class: 'project-init-info__input', type: "url", placeholder: "url" %>
                        </label>
                    </div>
                    <div class="project-init-info__cell">
                        <div class="project-init-info__furtiv-inp-cont">
                            or <span class="project-init-info__btn">Upload</span>
                            <label class="project-init-info__transp-mask">
                                <%= f.file_field 'inspiration_image1', id: "project-inspiration-image1", class: 'images-upload' %>
                            </label>
                        </div>
                    </div>
                    <div id="floatingBarSaving1" class="float-bar-saving">
                        <div class="blockG" id="rotateG_01"></div>
                        <div class="blockG" id="rotateG_02"></div>
                        <div class="blockG" id="rotateG_03"></div>
                        <div class="blockG" id="rotateG_04"></div>
                        <div class="blockG" id="rotateG_05"></div>
                        <div class="blockG" id="rotateG_06"></div>
                        <div class="blockG" id="rotateG_07"></div>
                        <div class="blockG" id="rotateG_08"></div>
                    </div>
                    <span id="loadIconSaving1" class="glyphicon glyphicon-ok load-icon-saving"></span>
                    <span id="loadIconError1" class="glyphicon glyphicon-remove load-icon-error"></span>
                </div>

                <div class="project-init-info__row">
                    <div class="project-init-info__cell"></div>
                    <div class="project-init-info__cell">
                        <label class="project-init-info__label">
                            <%= f.text_field "url_inspiration_image2", id: "project-url-inspiration-image2", class: 'project-init-info__input', type: "url", placeholder: "url" %>
                        </label>
                    </div>
                    <div class="project-init-info__cell">
                        <div class="project-init-info__furtiv-inp-cont">
                            or <span class="project-init-info__btn">Upload</span>
                            <label class="project-init-info__transp-mask">
                                <%= f.file_field 'inspiration_image2', id: "project-inspiration-image2", class: 'images-upload' %>
                            </label>
                        </div>
                    </div>
                    <div id="floatingBarSaving2" class="float-bar-saving">
                        <div class="blockG" id="rotateG_01"></div>
                        <div class="blockG" id="rotateG_02"></div>
                        <div class="blockG" id="rotateG_03"></div>
                        <div class="blockG" id="rotateG_04"></div>
                        <div class="blockG" id="rotateG_05"></div>
                        <div class="blockG" id="rotateG_06"></div>
                        <div class="blockG" id="rotateG_07"></div>
                        <div class="blockG" id="rotateG_08"></div>
                    </div>
                    <span id="loadIconSaving2" class="glyphicon glyphicon-ok load-icon-saving"></span>
                    <span id="loadIconError2" class="glyphicon glyphicon-remove load-icon-error"></span>
                </div>
                <div class="project-init-info__row">
                    <div class="project-init-info__cell"></div>
                    <div class="project-init-info__cell">
                        <label class="project-init-info__label">
                            <%= f.text_field "url_inspiration_image3", id: "project-url-inspiration-image3", class: 'project-init-info__input', type: "url", placeholder: "url" %>
                        </label>
                    </div>
                    <div class="project-init-info__cell">
                        <div class="project-init-info__furtiv-inp-cont">
                            or <span class="project-init-info__btn">Upload</span>
                            <label class="project-init-info__transp-mask">
                                <%= f.file_field 'inspiration_image3', id: "project-inspiration-image3", class: 'images-upload' %>
                            </label>
                        </div>
                    </div>
                    <div id="floatingBarSaving3" class="float-bar-saving">
                        <div class="blockG" id="rotateG_01"></div>
                        <div class="blockG" id="rotateG_02"></div>
                        <div class="blockG" id="rotateG_03"></div>
                        <div class="blockG" id="rotateG_04"></div>
                        <div class="blockG" id="rotateG_05"></div>
                        <div class="blockG" id="rotateG_06"></div>
                        <div class="blockG" id="rotateG_07"></div>
                        <div class="blockG" id="rotateG_08"></div>
                    </div>
                    <span id="loadIconSaving3" class="glyphicon glyphicon-ok load-icon-saving"></span>
                    <span id="loadIconError3" class="glyphicon glyphicon-remove load-icon-error"></span>
                </div>


                <!-- <div class="project-init-info__row no-display">
                    <div class="project-init-info__cell">Inspiration Images</div>
                    <div class="project-init-info__cell">
                        <div class="project-init-info__adm-img-cont l-cont">
                            <img class="l-el" src="">
                            <img class="l-el" src="">
                            <img class="l-el" src="">
                        </div>
                    </div>
                    <div class="project-init-info__cell"></div>
                </div> -->


                <div class="project-init-info__row">
                    <div class="project-init-info__cell">Room Type</div>
                    <div class="project-init-info__cell">
                        <label class="project-init-info__label">

                       <%= f.collection_select :product_category_id, ProductCategory.where(is_room: true).order(:name), :id, :name, {:class => 'project-init-info__select'} %>
                          <!--   <select class="project-init-info__select">
                                <option>Type 1</option>
                                <option>Type 2</option>
                                <option>Type 3</option>
                                <option>Type 4</option>
                                <option>Type 5</option>
                            </select> -->
                        </label>
                    </div>
                    <div class="project-init-info__cell"></div>
                </div>
                <div class="project-init-info__row">
                    <div class="project-init-info__cell">Ideal Room Size</div>
                    <div class="project-init-info__cell">
                        <table>
                            <tr>
                                <td>
                                    <span>Width</span>
                                    <label class="project-init-info__small-label">
                                        <%= f.number_field :width_ft, class: "project-init-info__small-input", id: 'project-width-ft', min: "0", step: "1" %>
                                    </label>
                                    <span>ft.</span>
                                </td>
                                <td>
                                    <label class="project-init-info__small-label">
                                        <%= f.number_field :width_in, class: "project-init-info__small-input", id: 'project-width-in', min: "0", step: "0.01" %>
                                    </label>
                                    <span>in.</span>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <span>Depth</span>
                                    <label class="project-init-info__small-label">
                                        <%= f.number_field :depth_ft, class: "project-init-info__small-input", id: 'project-depth-ft', min: "0", step: "1" %>
                                    </label>
                                    <span>ft.</span>
                                </td>
                                <td>
                                    <label class="project-init-info__small-label">
                                        <%= f.number_field :depth_in, class: "project-init-info__small-input", id: 'project-depth-in', min: "0", step: "0.01" %>
                                    </label>
                                    <span>in.</span>
                                </td>
                            </tr>
                        </table>
                    </div>
                    <div class="project-init-info__cell"></div>
                </div>
            <% end %>
        </div>
    </div>
</main>
<script>
 ;(function() {
    var urlInputs = document.querySelectorAll("input[type='url']");
    for (var i = 0, lim = urlInputs.length; i < lim; i += 1) {
        urlInputs[i].addEventListener("change", function() {
            var reg = /^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?$/;
            if(this.value.length !== 0 && !reg.test(this.value)) {
                this.classList.add("project-init-info__input--error");
            } else {
                this.classList.remove("project-init-info__input--error");
            }
        });
    };
 })();
</script>

app/views/design_projects/room_builder.html.erb
<% content_for :custom_scripts do %>
    <%= javascript_include_tag "specific/room_builder.js" %>
    <%= javascript_include_tag "specific/selected_furniture.js" %>
    <%= javascript_include_tag "specific/room_layout_editor.js" %>
    <%= javascript_include_tag "specific/furniture_board_editor.js" %>

<% end %>
<main class='room-builder'>
    <section class="main-tabs">
        <div class="l-wrapper">
            <%= link_to 'project info', designer_portal_path, class: "main-tabs__one-tab", id: 'project-info-tab' %>
            <%= link_to 'select items', designer_portal_select_items_path, class: "main-tabs__one-tab" %>
            <%= link_to 'room builder', designer_portal_room_builder_path, class: "main-tabs__one-tab main-tabs__one-tab--active", id: 'room-builder-tab' %>
            <%= link_to 'instructions', designer_portal_instructions_path, class: "main-tabs__one-tab", id: 'instructions-tab' %>
        </div>
    </section>
    <div class="l-wrapper">
        <div class="subtabs">
            <a class="subtabs__one-tab subtabs__one-tab--active" data-appearer="selected-furniture" href="#" id='selected-furniture-tab'>SELECED FURNITURE</a>
            <a class="subtabs__one-tab" data-appearer="room-layout" href="#" id='room-layout-tab'>ROOM LAYOUT</a>
            <a class="subtabs__one-tab" data-appearer="furniture-board" href="#" id='furniture-board-tab'>FURNITURE BOARD</a>

            <%= button_tag 'Submit Room', class: "subtabs__btn submit-room-btn layout-submit-room", style: "display: none", data: { url: "#{designer_portal_layout_submit_room_path}" } %>

            <%= button_tag 'Submit Room', class: "subtabs__btn submit-room-btn board-submit-room", style: "display: none", data: { url: "#{designer_portal_board_submit_room_path}" } %>

        </div>
        <div id="selected-furniture" class="js-tabs-block selected-furniture active-tab" data-project-id="<%= @design_project.id %>">
            <div class='selected-furniture-wrapper'>
                <%= render partial: 'selected_furniture' %>
            </div>
        </div>
        <div id="room-layout" class="js-tabs-block room-layout" data-url="<%= designer_portal_save_room_layout_path %>">
            <p class="room-layout__instr-text">Drag the line drawing to the room</p>
            <center><%= button_tag 'Set dimensions', class: "btn btn-guideline", id: 'set-dimensions' %></center>
            <div class='room-layout-wrapper'>
                <%= render partial: 'room_layout_editor' %>
            </div>
        </div>
        <div id="furniture-board" class="js-tabs-block furniture-board" data-url="<%= designer_portal_save_furniture_board_path %>">
            <p class="furniture-board__instr-text">Drag the images to the board</p>
            <div class='furniture-board-wrapper'>
                <%= render partial: 'furniture_board_editor' %>
            </div>
        </div>
    </div>
</main>