config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth/callbacks' }

  devise_scope :user do
    match 'create_user' => 'omniauth/callbacks#create_user', as: :create_user, via: :post
    match 'user_prompt' => 'omniauth/callbacks#user_prompt', as: :user_prompt, via: :get
  end

  devise_scope :user do
    mount Shoppe::Engine => "/shoppe"
  end

  get 'welcome/index'
  get 'about_us', to: 'welcome#about_us', as: 'about_us'
  get 'blog' => redirect("http://blog.gofourwalls.com"), as: 'blog'
  get 'account', to: 'welcome#account', as: 'account'

  resources :charges

  resources :products, only: [:index, :show] do
    member do
      post 'buy'
    end
    collection do
      get 'get_product'
    end
  end
  post 'products/destroy_img' => 'products#destroy_img'

  get "room_type", to: "product_categories#index_type"
  get "room_size", to: "product_categories#index_size"
  get "category_tree", to: "product_categories#category_tree"
  resources :product_categories, only: [:show]
  get "cart", to: "orders#show"
  delete "cart", to: "orders#destroy"
  post 'cart/:order_item_id', to: 'orders#remove', as: :remove_from_order

  match "checkout", to: "orders#checkout", as: "checkout", via: [:get, :patch]
  match "checkout/pay", to: "orders#payment", as: "checkout_payment", via: [:get, :post]
  match "checkout/confirm", to: "orders#confirmation", as: "checkout_confirmation", via: [:get, :post]
  match "order/:id/refresh_items", to: "orders#refresh_items", as: "refresh_order_items", via: [:get, :post]
  post "check_country", to: "orders#check_country", as: "check_country"
  post 'country_changing', to: 'orders#country_changing'
  post 'change_currency_checkout', to: 'orders#change_currency_checkout'
  post 'change_user_country', to: 'welcome#change_user_country'

  get 'room_editor', to: 'room#index'
  get 'room_editor/edit', to: 'room#edit'
  post 'room_editor/save', to: 'room#save'

  get 'designer-portal', to: 'design_projects#project_info'
  get 'designer-portal/select_items', to: 'design_projects#select_items'
  get 'designer-portal/room_builder', to: 'design_projects#room_builder'
  get 'designer-portal/instructions', to: 'design_projects#instructions'
  post 'designer-portal/create', to: 'design_projects#create'
  patch 'designer-portal/create', to: 'design_projects#create'
  patch 'designer-portal/add_to_room_builder', to: 'design_projects#add_to_room_builder'
  post 'designer-portal/items_filtering', to: 'design_projects#items_filtering'
  delete 'designer-portal/remove_product', to: 'design_projects#remove_product'

  get 'designer-portal/create_new', to: 'design_projects#create_new'

  patch 'designer-portal/save_room_layout', to: 'design_projects#save_room_layout'
  patch 'designer-portal/save_furniture_board', to: 'design_projects#save_furniture_board'
  patch 'designer-portal/layout_submit_room', to: 'design_projects#layout_submit_room'
  patch 'designer-portal/board_submit_room', to: 'design_projects#board_submit_room'

  get 'design_portals/:id', to: 'design_projects#edit'
  
  root 'welcome#index'

  get 'search', to: 'search#index'
  post 'change_user_country', to: 'welcome#change_user_country'

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  load_and_authorize_resource :class => 'Payment'
  before_filter { params[:id] && @payment = @order.payments.find(params[:id]) }

  def helper
    Helper.instance
  end

  class Helper
    include Singleton
    include ActionView::Helpers::NumberHelper
  end

  def new
    puts current_order.total

    if current_order.total < 0.01
      puts "balance is 0"
      flash[:notice] = "You cannot check out an empty order. Add a room to your basket first."
      redirect_to products_url
    end
  end

  def create
    # Amount in cents
    @order = current_order
    puts "in charges create controller "

    begin
      @amount = helper.number_with_precision(@order.total*100, precision: 0)

      if params[:stripeEmail] == nil
        params[:stripeEmail]= current_order.email_address
      end

      @customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :card  => params[:stripeToken]
      )
      currency = cookies[:currency] == 'ca' ? 'cad' : 'usd'
      @charge = Stripe::Charge.create(
        :customer    => @customer.id,
        :amount      => @amount,
        :description => "#{@order.first_name}'s Order",
        :currency    => currency
      )
    rescue Stripe::CardError => e
      flash[:error] = e.message
      Rails.logger.error e
      redirect_to :back
    end

    begin
      @payment = Payment.new(:amount => @order.total, :order_id => @order.id, :method =>'Stripe CC', :reference => @charge.id)
      @payment.save
    rescue
      flash[:error] = "Something went wrong with the payment transaction. Please check all information and try again. If the error persists, contact us to have it resolved."
      redirect_to charges_path
    end
  end

  def self.permission
    "Payment"
  end

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/create.html.erb
<div class="container-fluid cart-view">
    
	<h2 style="color: #f49224;">Thank you for your order!</h2>
	<p> We will process the order within 3 business days. You can check the status of your order any time on your <a href="http://gofourwalls.com/account">account page</a> upon logging in.</p>
	<p>You will be informed throughout the process of the order via email. Once your order is processed and all items are on their way to the local warehouse in your city, a Four Walls representative will contact you to confirm a delivery date and time window. </p>
	<p>If you have any questions, need further assistance or would like to provide feedback, please contact us at <a href="mailto:hi@gofourwalls.com">hi@gofourwalls.com</a>. We appreciate all feedback in making your experience with Four Walls better.</p>
	<% current_order.confirm! session[:order_id] = nil %>
</div>

app/views/charges/new.html.erb
<div class="container-fluid cart-view">
    <div class='breadcrumbs'>
        <p>
            <%= link_to 'VIEW CART', cart_path %>
            <span>>></span>
            <span><%= link_to 'BILLING AND SHIPPING INFO', checkout_path %></span>
            <span class="active">>></span>
            PAYMENT
            <span>>></span>
            REVIEW AND CONFIRM
        </p>
    </div>
    <% puts @params
    @order = current_order %>
          <div class="row ">
            <div class='col-md-8'>
              <div class='shopping-cart' data-order="<%= current_order.id %>">
                <div class='title'>
                  <p><b>SHOPPING CART</b></p>
                <div class='row'  style='margin:0'>
                  <div class='col-md-7 col-sm-7 col-xs-4'>
                  </div>
                  <div class='col-md-1 col-sm-1 col-xs-2 column-name'>
                    <center><span>PRICE</span></center>
                  </div>
                  <div class='col-md-1 col-sm-1 col-xs-2 column-name'>
                    <center><span class='quantity-title'>QTY</span></center>
                  </div>

                  <div class='col-md-2 col-sm-2 col-xs-2'>
                  </div>

                  <div class='col-md-1 col-sm-1 col-xs-2 column-name'>
                    <center><span>TOTAL</span></center>
                  </div>
                </div>
              </div>
              <div class='description'>
                <center><p>All products for a room will be delivered on one single day</p></center>
              </div>
              <div class='order-items-list'>
                <% current_order.order_items.each do |item| %>
                  <div class='order-item row' id="item_<%= item.id %>" data-item="<%= item.id %>">
                    <%= render partial: 'orders/order_item', locals: { item: item, order: current_order } %>
                  </div>
                <% end %>
              </div>
            </div>
        </div>
        <div class="col-md-4">

            <div class='checkout right-side-checkout'>
                <div class='order-summary'>
                    <div class='title'>
                        <p><b>ORDER SUMMARY</b></p>
                    </div>
                    <div class='box'>
                        <div class='inside-box'>
                            <div class='info' id='order-summary-info'>
                                <%= render 'orders/order_summary_info', :order => @order %>
                            </div>
                        </div>
                        <center>
                                <%= form_tag charges_path do %>
                                    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                                          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                                          data-description="<%=@order.first_name %>'s Order"
                                          data-amount="<%=@order.total*100%>"
                                        data-stripeEmail="<%= @order.email_address %>"></script>
                                    <script>
                                        $('.stripe-button-el').attr('id', "proceed-to-payment");
                                        $('#proceed-to-payment').find('span').removeAttr('style');
                                        $('#proceed-to-payment').css('visibility', 'hidden');
                                        $('#proceed-to-payment').removeClass('stripe-button-el');
                                        $('#proceed-to-payment').addClass('btn btn-default btn-lg btn-block');
                                        $('#proceed-to-payment').css('visibility', 'visible');
                                    </script>
                                <% end %>
                        </center>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class='checkout right-side-checkout'>
                <div class='order-summary'>
                    <div class='title' style="padding-left: 10px; ">
                        <p><b>BILLING ADDRESS</b></p>
                    </div>
                    <div class='box'>
                        <div class='inside-box'  style="padding: 10px; ">
                            <p><%= @order.first_name %> <%= @order.last_name %></p>
                            <p><%= @order.billing_address1 %>, <%= @order.billing_address4 %>,</p>
                            <p><%= @order.billing_postcode %>, <%= @order.billing_country.name %></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
              <div class='checkout right-side-checkout'>
                    <div class='order-summary'>
                        <div class='title' style="padding-left: 10px; ">
                        <p><b>SHIPPING ADDRESS</b></p>
                        </div>
                        <div class='box'>
                            <div class='inside-box' style="padding: 10px; ">
                                <p><%= @order.delivery_first_name%> <%= @order.delivery_last_name %></p>
                                <p><%= @order.delivery_address1%>, <%= @order.delivery_address4 %>,</p>
                                <p><%= @order.delivery_postcode %>, <%= @order.delivery_country.name %></p>
                            </div>
                        </div>
                    </div>
              </div>
        </div>


        <div class='col-md-4'>
            <div class='checkout right-side-checkout'>
                <div class='order-summary'>
                    <div class='title'>
                        <p><b>CONTACT INFO</b></p>
                    </div>
                    <div class='box'>
                        <div class='inside-box'>
                            <div class='info' id='order-summary-info'>
                                <%= render 'orders/contact_info' %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>